services:
  db:
    image: postgres:15
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
    environment:
      # Mapeando variáveis do Postgres para valores fixos ou lendo do shell
      # Para facilitar, vamos manter o padrão de dev aqui, ou ler do .env se os nomes fossem POSTGRES_...
      # Como definimos DB_USER no .env, o postgres imagem espera POSTGRES_USER.
      # Vamos manter hardcoded AQUI no local (backend isolado) ou passar explicitamente.
      - POSTGRES_DB=fluxar_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"

  backend:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    restart: on-failure
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    # AQUI ESTÁ A MUDANÇA:
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data_local:
