[mypy]
# Ativa o plugin do django-stubs
plugins = mypy_django_plugin.main

# Ignora erros de importação se a lib não tiver tipagem (opcional, mas útil)
ignore_missing_imports = True

[mypy.plugins.django-stubs]
# Aponta para o seu arquivo de settings
django_settings_module = core.settings
