# Generated by Django 5.1.15 on 2026-02-16 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_type'),
        ('goals', '0003_goal_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='accounts.account'),
        ),
    ]
