# Generated by Django 5.1.15 on 2026-03-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_goal_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='goaldeposit',
            name='type',
            field=models.CharField(choices=[('DEPOSIT', 'Aporte'), ('WITHDRAWAL', 'Resgate')], default='DEPOSIT', max_length=15),
        ),
    ]
