# Generated by Django 5.1.15 on 2026-03-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0005_goaldeposit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='goaldeposit',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='goaldeposit',
            name='transaction_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
