# Generated by Django 6.0 on 2026-04-17 13:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_goaldeposit_description_goaldeposit_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
