# Generated by Django 5.2.17 on 2026-10-08 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0007_alter_goal_image'),
        ('transactions', '0010_importacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='valor_antes_da_correcao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='goaldeposit',
            name='eh_correcao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goaldeposit',
            name='transacao_entrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='transactions.transaction'),
        ),
        migrations.AddField(
            model_name='goaldeposit',
            name='transacao_saida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='transactions.transaction'),
        ),
    ]
