# Generated by Django 5.1.15 on 2026-02-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_user_avatar_url_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'Usuário'), ('ADMIN', 'Administrador')], default='USER', max_length=10),
        ),
    ]
