# Generated by Django 5.2.17 on 2026-09-30 23:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_email_minusculo_e_pendentes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refresh_jti', models.CharField(max_length=64)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('ultimo_uso', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField()),
                ('encerrada_em', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'encerrada_em'], name='api_sessao_user_id_d90078_idx')],
            },
        ),
    ]
