# Generated by Django 5.2.17 on 2026-10-08 02:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_sessao'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravaDePlano',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chave', models.CharField(max_length=50)),
                ('plano', models.CharField(choices=[('COMMON', 'Comum'), ('PREMIUM', 'Premium'), ('PREMIUM_PLUS', 'Premium Plus')], max_length=20)),
                ('liberado', models.BooleanField(null=True)),
                ('limite', models.PositiveIntegerField(null=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('atualizada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('chave', 'plano'), name='trava_unica_por_plano')],
            },
        ),
    ]
