# Generated by Django 5.2.17 on 2026-10-09 10:10
"""
CPF, telefone, data de nascimento e renda passam a ficar criptografados no
banco, e o CPF deixa de ser único (LGPD-15, LGPD-18, LGPD-24).

Depois de as colunas virarem texto, os valores já gravados são lidos e
regravados pelo cursor, sem passar pelo campo do modelo: o campo atual
tentaria descriptografar o texto puro. Só as funções puras de
`core/criptografia.py` são usadas. Um valor que já é um token válido fica
como está, então a migração pode rodar de novo sem criptografar duas vezes.
O CPF passa a ser guardado só com os 11 dígitos.
"""
import datetime
from decimal import Decimal

import core.criptografia
from core.criptografia import InvalidToken, criptografar_texto, descriptografar_texto
from django.db import connection, migrations

COLUNAS = ('cpf', 'phone_number', 'date_of_birth', 'monthly_income')


def _ja_criptografado(valor):
    try:
        descriptografar_texto(valor)
    except (InvalidToken, UnicodeError):
        return False
    return True


def _normalizar(coluna, valor):
    """O valor antigo em texto, no formato que o campo novo devolve."""
    if coluna == 'cpf':
        return ''.join(caractere for caractere in valor if caractere.isdigit()) or None
    if coluna == 'date_of_birth':
        return datetime.date.fromisoformat(valor.strip()).isoformat()
    if coluna == 'monthly_income':
        return str(Decimal(valor.strip()))
    return valor


def _criptografar(coluna, valor):
    if valor is None or valor == '' or _ja_criptografado(valor):
        return valor
    texto = _normalizar(coluna, valor)
    return None if texto is None else criptografar_texto(texto)


def _cursor(apps, schema_editor):
    conexao = schema_editor.connection if schema_editor is not None else connection
    tabela = conexao.ops.quote_name(apps.get_model('api', 'User')._meta.db_table)
    return conexao.cursor(), tabela


def criptografar_dados_pessoais(apps, schema_editor):
    cursor, tabela = _cursor(apps, schema_editor)
    with cursor:
        cursor.execute(f'SELECT id, {", ".join(COLUNAS)} FROM {tabela}')
        for id_do_usuario, *valores in cursor.fetchall():
            novos = [_criptografar(coluna, valor) for coluna, valor in zip(COLUNAS, valores)]
            if novos != valores:
                cursor.execute(
                    f'UPDATE {tabela} SET {", ".join(f"{coluna} = %s" for coluna in COLUNAS)} WHERE id = %s',
                    [*novos, id_do_usuario],
                )


def descriptografar_dados_pessoais(apps, schema_editor):
    """Volta os valores para texto puro antes de as colunas voltarem aos tipos antigos."""
    cursor, tabela = _cursor(apps, schema_editor)
    with cursor:
        cursor.execute(f'SELECT id, {", ".join(COLUNAS)} FROM {tabela}')
        for id_do_usuario, *valores in cursor.fetchall():
            novos = [
                descriptografar_texto(valor) if valor and _ja_criptografado(valor) else valor
                for valor in valores
            ]
            if novos != valores:
                cursor.execute(
                    f'UPDATE {tabela} SET {", ".join(f"{coluna} = %s" for coluna in COLUNAS)} WHERE id = %s',
                    [*novos, id_do_usuario],
                )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_liberacao_para_testes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=core.criptografia.TextoCriptografado(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=core.criptografia.DataCriptografada(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='monthly_income',
            field=core.criptografia.DecimalCriptografado(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=core.criptografia.TextoCriptografado(blank=True, max_length=20, null=True),
        ),
        migrations.RunPython(criptografar_dados_pessoais, descriptografar_dados_pessoais),
    ]
