# Generated by Django 5.2.17 on 2026-10-09 10:52
"""
Log de auditoria sem nomes (LGPD-21, LGPD-22): `user` passa a SET_NULL e ganha
`usuario_ref`, o id interno do usuário, que fica no registro depois da
exclusão da conta (AD-030). Os registros já gravados são corrigidos na 0016,
numa transação à parte: no Postgres, o índice novo não pode ser criado na
mesma transação que atualiza as linhas da tabela.
"""
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_dados_pessoais_criptografados'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemlog',
            name='usuario_ref',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
