# Generated by Django 5.2.17 on 2026-10-09 10:52
"""
Log de auditoria sem nomes nem e-mails completos (LGPD-21, LGPD-22, LGPD-25).

Nos registros já gravados, a migração preenche `usuario_ref` a partir de
`user_id`, mascara os e-mails das descrições, tira o nome do administrador
das descrições de arquivamento, redefinição de senha e limpeza de dados, e
troca o nome em
`admin_name` pelo e-mail mascarado do administrador, ou por "Administrador"
quando o nome não aponta para uma única conta.
"""
import re

from django.db import migrations
from django.db.models import F

from api.utils.email_service import _mask_email

EMAIL = re.compile(r'[A-Za-z0-9._%+-]+@[A-Za-z0-9-]+(?:\.[A-Za-z0-9-]+)*\.[A-Za-z]{2,}')
# Descrições que levavam o nome do administrador no fim
COM_NOME_DO_ADMIN = re.compile(
    r'^(Conta arquivada pelo administrador|Senha redefinida pelo administrador|'
    r'Todos os dados financeiros e configurações foram limpos pelo administrador) .+$',
    re.S,
)
SISTEMA = 'Sistema'


def tirar_dados_pessoais(apps, schema_editor):
    SystemLog = apps.get_model('api', 'SystemLog')
    User = apps.get_model('api', 'User')
    SystemLog.objects.filter(user__isnull=False, usuario_ref__isnull=True).update(usuario_ref=F('user_id'))

    emails_por_nome = {}
    for nome, email in User.objects.filter(role='ADMIN').values_list('name', 'email'):
        emails_por_nome.setdefault(nome, []).append(email)

    for log in SystemLog.objects.only('id', 'description', 'admin_name').iterator():
        descricao = EMAIL.sub(lambda achado: _mask_email(achado.group(0)), log.description)
        descricao = COM_NOME_DO_ADMIN.sub(r'\1.', descricao)
        admin = log.admin_name
        if EMAIL.fullmatch(admin):
            admin = _mask_email(admin)
        elif admin != SISTEMA and '*@' not in admin:
            # Um nome: vira o e-mail mascarado da única conta de admin com ele
            emails = emails_por_nome.get(admin, [])
            admin = _mask_email(emails[0]) if len(emails) == 1 else 'Administrador'
        if (descricao, admin) != (log.description, log.admin_name):
            SystemLog.objects.filter(pk=log.pk).update(description=descricao, admin_name=admin)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_log_de_auditoria_sem_nomes'),
    ]

    operations = [
        migrations.RunPython(tirar_dados_pessoais, migrations.RunPython.noop),
    ]
