# Generated by Django 5.2.17 on 2026-10-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_log_de_auditoria_dados_antigos'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='exclusao_agendada_para',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='exclusao_pedida_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
