# Generated by Django 5.2.17 on 2026-10-09 22:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_pedido_de_exclusao'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroDeExclusao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usuario_id', models.UUIDField(unique=True)),
                ('pedida_em', models.DateTimeField(blank=True, null=True)),
                ('excluida_em', models.DateTimeField()),
                ('executada_por', models.CharField(choices=[('USUARIO', 'Usuário'), ('ROTINA', 'Rotina diária'), ('ADMIN', 'Administrador')], max_length=10)),
            ],
        ),
    ]
