# Generated by Django 5.2.17 on 2026-10-09 22:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def sem_aceite_e_sem_consentimento(apps, schema_editor):
    """
    Todos os usuários existentes ficam sem o aceite da versão nova e sem o
    consentimento de melhoria do produto, que não pode ser presumido (LGPD-39).
    Os campos antigos terms_accepted e terms_accepted_at ficam como histórico.
    """
    User = apps.get_model('api', 'User')
    User.objects.update(versao_dos_termos_aceita=None, consentimento_melhoria=False)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_registrodeexclusao'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='consentimento_melhoria',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='versao_dos_termos_aceita',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='AceiteDosTermos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('versao', models.CharField(max_length=20)),
                ('aceito_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aceites_dos_termos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-aceito_em'],
            },
        ),
        migrations.CreateModel(
            name='DecisaoDeConsentimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consentiu', models.BooleanField()),
                ('versao_da_politica', models.CharField(max_length=20)),
                ('decidido_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisoes_de_consentimento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-decidido_em'],
            },
        ),
        migrations.RunPython(sem_aceite_e_sem_consentimento, migrations.RunPython.noop),
    ]
