# Generated by Django 5.2.17 on 2026-10-10 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_termos_por_versao_e_consentimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemlog',
            name='admin_ref',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='antes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='depois',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='usuario_email',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
