# Generated by Django 6.0 on 2025-12-17 13:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('limit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('closing_day', models.IntegerField(help_text='Dia de fechamento da fatura (1-31)')),
                ('due_day', models.IntegerField(help_text='Dia de vencimento da fatura (1-31)')),
                ('institution', models.CharField(blank=True, help_text='Código ou nome da instituição para ícone', max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('CHECKING', 'Conta Corrente'), ('SAVINGS', 'Poupança'), ('WALLET', 'Carteira'), ('INVESTMENT', 'Investimento')], default='CHECKING', max_length=20)),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('institution', models.CharField(blank=True, help_text="Código ou nome da instituição para ícone (ex: 'nubank', 'itaú')", max_length=50, null=True)),
                ('color', models.CharField(blank=True, help_text='Cor hexadecimal para exibição (ex: #7F22E2)', max_length=7, null=True)),
                ('is_manual', models.BooleanField(default=True, help_text='Se True, movimentação é manual. Se False, virá de integração externa.')),
                ('external_id', models.CharField(blank=True, help_text='ID da conta na API externa de Open Finance', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'type'], name='accounts_ac_user_id_b5e7fb_idx')],
            },
        ),
        migrations.CreateModel(
            name='CreditCardInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('OPEN', 'Aberta'), ('CLOSED', 'Fechada'), ('PAID', 'Paga')], default='OPEN', max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('closing_date', models.DateField()),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='accounts.creditcard')),
            ],
            options={
                'unique_together': {('card', 'month', 'year')},
            },
        ),
    ]
