# Generated by Django 5.1.15 on 2026-01-02 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Conta usada para pagar a fatura deste cartão', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_cards', to='accounts.account'),
        ),
    ]
