# Generated by Django 5.1.15 on 2026-02-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_creditcard_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('CHECKING', 'Conta Corrente'), ('SAVINGS', 'Poupança'), ('WALLET', 'Carteira'), ('INVESTMENT', 'Investimento'), ('PIGGY_BANK', 'Cofrinho')], default='CHECKING', max_length=20),
        ),
    ]
