# Generated by Django 5.1.15 on 2026-04-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Saldo atual calculado (inicial + receitas - despesas)', max_digits=15),
        ),
    ]
