# Generated by Django 5.2.17 on 2026-10-03 01:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_balance'),
        ('transactions', '0009_transaction_purchase_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PagamentoDeFatura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('data', models.DateField()),
                ('chave', models.UUIDField(blank=True, null=True)),
                ('estornado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.account')),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='accounts.creditcardinvoice')),
                ('fatura_seguinte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.creditcardinvoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos_de_fatura', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemDePagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PAGA', 'Paga'), ('DIVIDIDA', 'Dividida'), ('MOVIDA', 'Movida')], max_length=10)),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('descricao_original', models.CharField(blank=True, max_length=255)),
                ('compra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='transactions.transaction')),
                ('restante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='transactions.transaction')),
                ('pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='accounts.pagamentodefatura')),
            ],
        ),
        migrations.AddConstraint(
            model_name='pagamentodefatura',
            constraint=models.UniqueConstraint(condition=models.Q(('chave__isnull', False)), fields=('user', 'chave'), name='pagamento_chave_unica_por_usuario'),
        ),
    ]
