# Generated by Django 5.2.17 on 2026-10-10 10:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_corrige_faturas'),
        ('goals', '0010_trocos'),
        ('transactions', '0014_divisao_do_salario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisaoDoSalario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recebimento_ref', models.UUIDField(db_index=True)),
                ('chave', models.UUIDField(blank=True, null=True)),
                ('valor_recebido', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('livre', models.DecimalField(decimal_places=2, max_digits=12)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('desfeita_em', models.DateTimeField(blank=True, null=True)),
                ('conta_de_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.account')),
                ('recebimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='transactions.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisoes_do_salario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GestaoDoSalario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorias_configuradas', models.BooleanField(default=False)),
                ('plano_salvo', models.BooleanField(default=False)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('categorias', models.ManyToManyField(blank=True, related_name='+', to='transactions.category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gestao_do_salario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemDaDivisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField()),
                ('nome_da_parte', models.CharField(max_length=60)),
                ('tipo_de_destino', models.CharField(blank=True, choices=[('ACCOUNT', 'Conta'), ('GOAL', 'Meta'), ('SALARY_ACCOUNT', 'Fica na conta do salário')], default='', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reduzida', models.BooleanField(default=False)),
                ('transfer_id', models.UUIDField(blank=True, null=True)),
                ('conta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.account')),
                ('divisao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='salario.divisaodosalario')),
                ('meta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='goals.goal')),
                ('transacao_entrada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='transactions.transaction')),
                ('transacao_saida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='transactions.transaction')),
            ],
            options={
                'ordering': ['ordem', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ParteDoPlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField()),
                ('nome', models.CharField(max_length=60)),
                ('tipo_de_regra', models.CharField(choices=[('FIXED', 'Valor fixo'), ('PERCENT', 'Percentual do salário')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo_de_destino', models.CharField(blank=True, choices=[('ACCOUNT', 'Conta'), ('GOAL', 'Meta'), ('SALARY_ACCOUNT', 'Fica na conta do salário')], max_length=20, null=True)),
                ('referencia', models.CharField(blank=True, choices=[('ESSENCIAL', 'Essencial'), ('DISPENSAVEL', 'Dispensável')], default='', max_length=20)),
                ('conta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.account')),
                ('gestao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partes', to='salario.gestaodosalario')),
                ('meta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='goals.goal')),
            ],
            options={
                'ordering': ['ordem', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='divisaodosalario',
            constraint=models.UniqueConstraint(condition=models.Q(('chave__isnull', False)), fields=('user', 'chave'), name='divisao_chave_unica_por_usuario'),
        ),
        migrations.AddConstraint(
            model_name='divisaodosalario',
            constraint=models.UniqueConstraint(condition=models.Q(('desfeita_em__isnull', True)), fields=('recebimento_ref',), name='divisao_ativa_unica_por_recebimento'),
        ),
    ]
