# Generated by Django 6.0 on 2026-01-05 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_category_is_template_category_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('COMPLETED', 'Concluída')], default='COMPLETED', max_length=10),
        ),
    ]
