# Generated by Django 6.0 on 2026-01-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transfer_group',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transfer_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='ID agrupador de transferências (origem/destino)', null=True),
        ),
        migrations.DeleteModel(
            name='TransferGroup',
        ),
    ]
