# Generated by Django 6.0 on 2026-01-07 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_remove_transaction_transfer_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='recurring_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_transactions', to='transactions.recurringtransaction'),
        ),
    ]
