# Generated by Django 5.2.17 on 2026-10-03 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_corrige_saldos'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
