# Generated by Django 5.2.17 on 2026-10-07 23:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_corrige_faturas'),
        ('transactions', '0009_transaction_purchase_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrecaoDeCategoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
                ('descricao_normalizada', models.CharField(db_index=True, max_length=255)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='categoria_sugerida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fitid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='import_batch',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('fitid__isnull', False)), fields=('account', 'fitid'), name='fitid_unico_por_conta'),
        ),
        migrations.AddField(
            model_name='correcaodecategoria',
            name='categoria_antes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='transactions.category'),
        ),
        migrations.AddField(
            model_name='correcaodecategoria',
            name='categoria_depois',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='transactions.category'),
        ),
        migrations.AddField(
            model_name='correcaodecategoria',
            name='conta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='correcaodecategoria',
            name='transacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='transactions.transaction'),
        ),
        migrations.AddField(
            model_name='correcaodecategoria',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correcoes_de_categoria', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='correcaodecategoria',
            index=models.Index(fields=['user', 'descricao_normalizada', '-criada_em'], name='transaction_user_id_27794b_idx'),
        ),
    ]
