# Generated by Django 5.2.17 on 2026-10-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_classes_de_despesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='divisao_do_salario',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
